### PR TITLE
More settings functionality

### LINKED ISSUE #88: Controls menu
We have the infrastructure to allow rebinding keys, but no graphical way to do it yet

### LINKED ISSUE #94: Bullets don't break blocks properly
Not sure when this functionality got broken, but when a bullet hits a breakable block it no longer generates particles or gives points.

### PR DESCRIPTION
**Pull request by jojonium**
### New

  - Controls menu where you can rebind all controller and keyboard inputs (Fixes #88)
  - Settings and controls are remembered with a cookie
  - Disable glow effect setting
  - Disable splatter effects setting
  - Overkill damage is converted into velocity
  - Sound effects for pickups
  - Sound effect for enemy death

### Changed

  - "Enter fullscreen" button moved to settings menu
  - Menu select sound effect now plays when the button is pressed, rather than released
  - Enemies that drop power ups don't drop pickups

### Fixed

  - Breakable blocks create particles and give points again (Fixes #94)

### CODE REVIEW

File: static/game/controlsmenu.js [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+        func: () => {
+          if (getUsingKeyboard()) {
+            button.key = "Press a key...";
+            getNextKey().then(newKey => {
+              button.key = newKey;
+              saveControls();
+            });
+          } else {
+            const oldButton = button.gpButtonIndex;
+            // @ts-ignore I know we're assigning a string to a number, but it's
```
Comment (bandaloo) [inline static/game/controlsmenu.js]: There has to be a better way. This would be the only time we're using `@ts-ignore`

File: static/game/controlsmenu.js [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+          x + this.width / 2 - this.itemMargin + this.itemWidth / 2,
+          y + this.itemHeight / 2
+        ),
+        this.textStyle,
+        "right",
+        "middle",
+        this.textFillStyle
+      );
+    }
+  }
```
Comment (bandaloo) [inline static/game/controlsmenu.js]: Kind of don't like that this code is copy-pasted all over. This exact block appears like three (four?) times.

File: static/game/creature.js [hunk 3]
```diff
@@ -354,9 +354,16 @@ export class Creature extends Entity {
    * Decreases the creature's current health by the given amount, killing it if
    * necessary
    * @param {number} amt the amount of damage dealt
+   * @param {Vector} [dir] the direction the damage came from
    */
-  takeDamage(amt) {
+  takeDamage(amt, dir = this.vel.norm2()) {
     const damageToTake = defenseFunc(amt, this.defense);
+    // convert overkill damage into velocity
```
Comment (bandaloo) [inline static/game/creature.js]: Cool

File: static/game/deathscreen.js [hunk 4]
```diff
@@ -61,6 +75,18 @@ export class DeathScreen extends Menu {
    * @override
    */
   draw() {
+    const cursor =
+      this.enteringUsername && this.cursorBlinkCounter % 100 < 50 ? "_" : " ";
```
Comment (bandaloo) [inline static/game/deathscreen.js]: suppress default of the key events when entering the username. pressing space takes you to the bottom of the page (even if you don't allow space, it shouldn't do that)

File: static/game/pickup.js [hunk 5]
```diff
@@ -74,9 +75,11 @@ export class Pickup extends Entity {
    */
   getPicked(entity) {
     if (this.pickupType === PickupEnum.bomb) {
+      playSound("bomb-pickup");
       // checking for existance of hero shouldn't be necessary
       /** @type {Hero} */ (entity).addBombs(1);
     } else if (this.pickupType === PickupEnum.health) {
+      playSound("health-pickup");
```
Comment (bandaloo) [inline static/game/pickup.js]: nice

File: static/index.html [hunk 6]
```diff
@@ -11,25 +11,34 @@
...
-        space <i>(or A/cross)</i>: select<br />
-        tab <i>(or B/circle)</i>: back<br />
-        f: fullscreen<br />
-        p <i>(or start)</i>: pause<br />
+      <p>
+        <b>Try using a controller for analog controls!</b><br />
       </p>
+      <table>
+        <tr>
+          <td>move</td> <td>wasd</td> <td>left stick</td>
```
Comment (bandaloo) [inline static/index.html]: Can you have the right-most column right justified?

File: static/style.css [hunk 7]
```diff
@@ -81,16 +71,21 @@ div#loading-bar-fill {
...
 }
 
+table tr > td:first-child {
+  text-align: left;
+}
+
+table tr > td {
+  text-align: center;
+  padding: 0 1em;
+}
```
Comment (bandaloo) [inline static/style.css]: Make the rightmost columns right aligned

File: static/index.html [hunk 8]
```diff
@@ -11,25 +11,34 @@
...
-        🎮🎮🎮 <b>Try using a controller for analog controls!</b> 🎮🎮🎮<br />
-        wasd <i>(or left sick)</i>: move<br />
-        arrow keys <i>(or right stick)</i>: shoot<br />
-        space <i>(or LB/L1)</i>: bomb<br />
-        space <i>(or A/cross)</i>: select<br />
-        tab <i>(or B/circle)</i>: back<br />
-        f: fullscreen<br />
-        p <i>(or start)</i>: pause<br />
+      <p>
+        <b>Try using a controller for analog controls!</b><br />
```
[the remark this answers is not in the document]
Comment (jojonium) [reply static/index.html]: No

File: static/game/controlsmenu.js (hunk 1 above)
Comment (jojonium) [reply static/game/controlsmenu.js]: The better way would be a lot more complicated. If we're going to use loosey goosey JavaScript we might as well take advantage of it when we can. I think a simple case like this along with an explanatory comment is clear enough and it doesn't cause any issues.

File: static/index.html (hunk 8 above)
[the remark this answers is not in the document]
Comment (bandaloo) [reply static/index.html]: It doesn't have to be three but put one back.

File: static/game/block.js [hunk 9]
```diff
@@ -27,13 +31,20 @@ export class Block {
...
+    testEntity.width = getBlockWidth();
+    testEntity.height = getBlockHeight();
+    if (testEntity.onScreen()) {
+      playSound("hit-breakable");
+      for (let i = 0; i < 3; i++) {
+        const p = new Particle(worldVec, "black", EffectEnum.square, 5, 3);
+        p.lineWidth = 1;
+        p.strokeStyle = "white";
+        addParticle(p);
+      }
```
[the remark this answers is not in the document]
Comment (jojonium) [reply static/game/block.js]: Only if it grants points (i.e. gem blocks broken by enemies don't make noise)

File: static/game/controlsmenu.js (hunk 1 above)
Comment (bandaloo) [reply static/game/controlsmenu.js]: Ya, sure, as long as I'm allowed to fix it.

File: static/modules/displaymanager.js [hunk 10]
```diff
@@ -285,9 +321,11 @@ export function toggleFullscreen() {
     // enter fullscreen
     displayManager.displayCanvas.width = displayManager.screenWidth;
     displayManager.displayCanvas.height = displayManager.screenHeight;
+    settings["Fullscreen"].value = true;
```
[the remark this answers is not in the document]
Comment (jojonium) [reply static/modules/displaymanager.js]: There's already a whole button dedicated to it

File: static/game/settings.js [hunk 11]
```diff
@@ -1,28 +1,142 @@
...
+      saveSettings();
+    },
+    update() {
+      return;
+    }
+  },
+  "Camera following strategy": {
+    value: true,
+    getDisplayVal() {
+      return this.value ? "tight" : "loose";
```
[the remark this answers is not in the document]
Comment (jojonium) [reply static/game/settings.js]: Removed in 706c426

File: static/game/controlsmenu.js (hunk 2 above)
Comment (jojonium) [reply static/game/controlsmenu.js]: Moved into Menu class in 706c426

File: static/game/deathscreen.js (hunk 4 above)
Comment (jojonium) [reply static/game/deathscreen.js]: Fixed in 706c426

File: static/index.html (hunk 6 above)
Comment (jojonium) [reply static/index.html]: Implemented in 706c426

File: static/style.css (hunk 7 above)
Comment (jojonium) [reply static/style.css]: Implemented in 706c426

File: static/index.html (hunk 8 above)
[the remark this answers is not in the document]
Comment (jojonium) [reply static/index.html]: Restored by 7ce9410

File: static/game/scoresmenu.js [hunk 12]
```diff
@@ -52,9 +52,9 @@ export class ScoresMenu extends Menu {
           this.setItems(
             JSON.parse(obj.message)
               .scores.sort((a, b) => b.score - a.score)
-              .map(val => {
+              .map((val, i) => {
                 return {
-                  text: val.score + "\t" + val.username,
+                  text: `${i + 1})  ${val.score}\t${val.username}`,
```
Comment (Matt-Puentes) [inline static/game/scoresmenu.js]: nice

File: static/main.js [hunk 13]
```diff
@@ -164,6 +160,9 @@ export function resetDemo() {
   }
 }
 
+if (navigator.userAgent.indexOf("Mac") !== -1) 
+  document.getElementById("controller-text").textContent += " 🎮";
+
```
Comment (Matt-Puentes) [inline static/main.js]: yeah bud let's get rid of this ok

Comment (bandaloo) [inline static/main.js]: Let's keep the meme commits to a minimum of 0 in general
