### PR TITLE
Collison fixes

### LINKED ISSUE #29: Collision circles
It would be nice if some entities could have collision circles rather than collision boxes

### LINKED ISSUE #58: Bullets going through walls
This will happen if they get too fast. For whatever reason, they still go through the right and bottom walls but not the left and top walls.

### PR DESCRIPTION
**Pull request by Matt-Puentes**
Collision Rewritten
Collision math now done with "CollisionShape" object
Collision can handle Box/Box, Circle/Circle, and Box/Circle collision
Entities can have two different shapes, one for colliding with terrain and one for all other entities. This removes the need for the "Cheat" functions.
resolves #29 
Hopefully resolves #58, more testing needed.

### CODE REVIEW

**Comment by jojonium** [comment]
No entities bounce now. Check `Entity.occludedByWalls`, `Entity.reflectsOffWalls`, and `Entity.wallReflectSpeed`

**Comment by Matt-Puentes** [comment]
Confirmed to resolve #58

File: static/game/hero.js [hunk 1]
```diff
@@ -43,6 +44,16 @@ export class Hero extends Creature {
     this.score = 0;
     this.setBombDamage(18);
 
+    // Manually set the collision shape to allow for a smaller hitbox
+    const collisionShape = new Circle(
+      (DEFAULT_SIZE - CHEAT_RADIUS) / 2,
```
Comment (bandaloo) [inline static/game/hero.js]: nice

File: static/game/powerups/quickshot.js [hunk 2]
```diff
@@ -2,7 +2,7 @@ import { PowerUp } from "../powerup.js";
 import { Vector } from "../../modules/vector.js";
 import { Creature } from "../creature.js";
 
-const MAX_BULLET_SPEED = 50;
+const MAX_BULLET_SPEED = 24;
```
Comment (bandaloo) [inline static/game/powerups/quickshot.js]: width and height of a bullet is actually also 24, so we can add the radius of the smallest bullet to this. the new speed of light could be 24 + 12 - 1 = 35 (the minus one is for safety so it can't jump exactly half)

we could also just test this empirically

File: static/main.js [hunk 3]
```diff
@@ -138,7 +139,7 @@ export function resetDemo() {
     const powerup_num = Math.floor(Math.random() * additional_powerups) + 1;
 
     for (let p = 0; p < powerup_num; p++) {
-      /** @type {Vector} */
+      /** @type {number} */
```
Comment (bandaloo) [inline static/main.js]: cool, i also noticed this incorrect type and fixed this in my branch i think

File: static/modules/entity.js [hunk 4]
```diff
@@ -48,19 +54,6 @@ export class Entity {
...
-
-  /** @type {boolean} */
-  collidesRight = true;
-
-  /** @type {boolean} */
-  collidesTop = true;
-
-  /** @type {boolean} */
-  collidesBottom = true;
-
```
Comment (bandaloo) [inline static/modules/entity.js]: thrilled we can finally move these properties out of entity

File: static/modules/entity.js [hunk 5]
```diff
@@ -114,18 +128,76 @@ export class Entity {
...
+    } else if (this.collisionType == "Box") {
+      return new Box(this.width, this.height, this.pos, this.vel);
+    } else if (this.collisionType == "Circle") {
+      return new Circle(
+        Math.min(this.width, this.height) / 2,
+        this.pos,
+        this.vel
+      );
+    }
+    return new CollisionShape("undefined", this.pos, this.vel);
```
Comment (bandaloo) [inline static/modules/entity.js]: remember to change this when you address the comment about using the string "undefined"

File: static/modules/entity.js [hunk 6]
```diff
@@ -114,18 +128,76 @@ export class Entity {
...
+  }
+
+  /**
+   * Returns the terrainCollisionShape of the entity.
```
Comment (bandaloo) [inline static/modules/entity.js]: nit: can we say "terrain collision shape" instead of "terrainCollisionShape" in this doc comment so we don't have symbol names in the description part? if we rename this might get missed, and it keeps the description higher level

File: static/game/hero.js [hunk 7]
```diff
@@ -1,13 +1,14 @@
...
 import { buttons } from "../modules/buttons.js";
 import { addParticle, toggleGuiElement } from "../modules/gamemanager.js";
 import { Particle, EffectEnum } from "./particle.js";
 import { PowerUp, POWER_UP_POINTS_FACTOR } from "./powerup.js";
-import { Creature } from "./creature.js";
 import { playSound, getSound } from "../modules/sound.js";
+import { Circle, Box } from "../modules/collision.js";
 
-const DEFAULT_SIZE = 50;
+const DEFAULT_SIZE = 130;
```
Comment (bandaloo) [inline static/game/hero.js]: lol change this back

File: static/modules/entity.js [hunk 8]
```diff
@@ -114,18 +128,76 @@ export class Entity {
...
     /** @type {Vector} */
     this.acc = acc;
+    this.collisionType = "Circle";
+  }
+
+  /**
+   * Set the collisionShape of the entity. Give no arguments to reset the shape
+   * to be calculated each call of getCollisonShape
+   * @param {CollisionShape | undefined} collisionShape
+   * @returns {void}
```
Comment (bandaloo) [inline static/modules/entity.js]: I made the same nitpick earlier, but I kind of like when documentation comments don't have symbol names in them because it keeps it higher level and is easier to refactor (less likely to go out of date accidentally). I'd just say "collision shape" instead of collisionShape. This applies to documentation below too.

File: static/modules/entity.js [hunk 9]
```diff
@@ -114,18 +128,76 @@ export class Entity {
     this.vel = vel;
     /** @type {Vector} */
     this.acc = acc;
+    this.collisionType = "Circle";
+  }
+
+  /**
+   * Set the collisionShape of the entity. Give no arguments to reset the shape
+   * to be calculated each call of getCollisonShape
+   * @param {CollisionShape | undefined} collisionShape
```
Comment (bandaloo) [inline static/modules/entity.js]: This typing `{CollisionShape | undefined}` is redundant I think.
You should be able to just do `@param {CollisionShape} [collisionShape]` meaning it's optional (can be undefined)

File: static/modules/entity.js [hunk 10]
```diff
@@ -100,6 +93,27 @@ export class Entity {
   /** @type {boolean} */
   pausable = true;
 
+  /**
+   * Determines what type of collision will be generated when getCollisionShape
+   * is called and collisionShape is undefined.
+   */
+  /** @type {"Box"|"Circle"|"undefined"} */
```
Comment (bandaloo) [inline static/modules/entity.js]: Calling it "undefined" might cause some headaches later when we're trying to see if collisionType is actually "undefined" or `undefined` being coerced into "undefined". Can we pick a different name for this even if it's "not defined"?

File: static/modules/entity.js [hunk 11]
```diff
@@ -114,18 +128,76 @@ export class Entity {
...
+      this.terrainCollisionShape.vel = this.vel;
+      return this.terrainCollisionShape;
+    }
+    return this.getCollisionShape();
   }
 
   onScreen() {
     const { width: screenWidth, height: screenHeight } = getScreenDimensions();
-    const screenEntity = new Entity(
+    const screenBox = new Box(
```
Comment (bandaloo) [inline static/modules/entity.js]: Sweet, it always felt a little wrong to have to create a dummy screen entity in order to check for collision.

File: static/modules/entity.js [hunk 12]
```diff
@@ -114,18 +128,76 @@ export class Entity {
...
+  }
+
+  /**
+   * Returns the terrainCollisionShape of the entity.
+   * If the entity has a collisionEntity property, that shape is updated to the
+   * current position and returned. Otherwise, the collisionShape is returned.
+   * @returns {CollisionShape}
+   */
+  getTerrainCollisionShape() {
+    if (this.terrainCollisionShape !== undefined) {
```
Comment (bandaloo) [inline static/modules/entity.js]: What's the point of having the "undefined" CollisionType if you can just have the actual CollisionShape be undefined? It also looks like you never check to see if the CollisionType equals the string "undefined" (which I recommended changing the name of earlier) which suggests that this is redundant even in the current implementation.

File: static/modules/gamemanager.js [hunk 13]
```diff
@@ -71,6 +71,8 @@ class GameManager {
   /** @type {boolean} */
   gamePause = false;
 
+  displayCanvas = undefined;
+
```
Comment (bandaloo) [inline static/modules/gamemanager.js]: Why did this get added?

Edit: This also has literally no references but one in a function that also has literally no references itself, so get rid of it.

File: static/modules/gamemanager.js [hunk 14]
```diff
@@ -95,6 +97,13 @@ class GameManager {
     }
   }
 
+  addDisplayToDiv(id) {
+    const displayDiv = document.getElementById(id);
+    if (displayDiv != undefined) {
+      displayDiv.appendChild(this.displayCanvas);
+    }
+  }
+
```
Comment (bandaloo) [inline static/modules/gamemanager.js]: Hmm. Why did this get added? This got moved over to displaymanager I'm pretty sure...
It also has literally no references but itself so just get rid of it.

File: static/modules/gamemanager.js [hunk 15]
```diff
@@ -243,7 +252,12 @@ class GameManager {
...
           if (collideEntities !== undefined) {
             for (let k = 0; k < collideEntities.length; k++) {
-              if (isColliding(targetEntity, collideEntities[k])) {
+              if (
+                !collide(
+                  targetEntity.getCollisionShape(),
+                  collideEntities[k].getCollisionShape()
+                ).isZeroVec()
+              ) {
                 targetEntity.collideWithEntity(collideEntities[k]);
```
Comment (bandaloo) [inline static/modules/gamemanager.js]: Does this mean you perform the collision check twice? Once to check if the collide doesn't result in the zero vec, and another time to actually run the collision.

File: static/modules/entity.js [hunk 16]
```diff
@@ -114,18 +128,76 @@ export class Entity {
...
+      screenWidth,
+      screenHeight,
       new Vector(screenWidth / 2, screenHeight / 2).add(
         getCameraOffset().mult(-1)
       )
     );
-    screenEntity.width = screenWidth;
-    screenEntity.height = screenHeight;
-    return isColliding(this, screenEntity);
+    return !collide(this.getCollisionShape(), screenBox).isZeroVec() || true;
```
Comment (bandaloo) [inline static/modules/entity.js]: ummmm... this always returns true??

does this mean you've been testing with every entity being reported as on screen?

File: static/game/bullet.js [hunk 17]
```diff
@@ -128,6 +131,9 @@ export class Bullet extends Entity {
     // remove the bullet if it's not supposed to bounce
     if (!this.reflectsOffWalls) {
       this.deleteMe = true;
+    } else {
+      this.reflectNum--;
```
Comment (bandaloo) [inline static/game/bullet.js]: Why do we need a number for the amount of times its reflected?

File: static/game/bullet.js [hunk 18]
```diff
@@ -94,6 +96,7 @@ export class Bullet extends Entity {
 
   destroy() {
     // execute all on-destroy functions
+    if (this.good) console.log("--DEAD--");
```
Comment (bandaloo) [inline static/game/bullet.js]: get rid of this console log

File: package.json [hunk 19]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "afterlight-caves",
-  "version": "0.7.1",
+  "version": "0.8.1",
```
Comment (jojonium) [inline package.json]: Bumping the minor version resets the patch number, so this should be 0.8.0

File: static/game/bullet.js [hunk 20]
```diff
@@ -62,18 +66,16 @@ export class Bullet extends Entity {
...
-          // impart momentum
-          const size = (c.width * c.height) / 300;
-          c.vel = c.vel.add(this.vel.mult(this.knockback / size));
-          // call onHitEnemy functions
-          for (const ohe of this.onHitEnemy) {
-            if (ohe.func) ohe.func(this, ohe.data, c);
-          }
-          this.deleteMe = true;
+        // deal basic damage
+        c.takeDamage(this.damage);
```
Comment (jojonium) [inline static/game/bullet.js]: `Creature.takeDamage()` takes a second optional argument of the direction the damage came from now, for the purpose of converting overkill damage into velocity. Make this `c.takeDamage(this.damage, this.vel.norm2())`

File: static/index.html [hunk 21]
```diff
@@ -10,7 +10,7 @@
     <div id="gamediv-holder">
       <h1 class="title">Afterlight Caves</h1>
       <span id="version"
-        >Beta version 0.7.1 (<a
+        >Beta version 0.8.1 (<a
```
Comment (jojonium) [inline static/index.html]: 0.8.0

File: package-lock.json [hunk 22]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "afterlight-caves",
-  "version": "0.7.1",
+  "version": "0.8.1",
```
Comment (jojonium) [inline package-lock.json]: 0.8.0

File: static/game/powerups/quickshot.js (hunk 2 above)
Comment (Matt-Puentes) [reply static/game/powerups/quickshot.js]: 24 is the maximum I found experimentally
We can try to increase it later on by using the bullet's velocity with collision detection (marking it as "fast" like box2D is a good solution but it's one for another PR.

File: static/main.js (hunk 3 above)
Comment (Matt-Puentes) [reply static/main.js]: nice

File: static/modules/gamemanager.js (hunk 14 above)
Comment (Matt-Puentes) [reply static/modules/gamemanager.js]: I don't recall how this got added, will be removed.

File: static/modules/gamemanager.js (hunk 15 above)
Comment (Matt-Puentes) [reply static/modules/gamemanager.js]: No, "Collide" checks to see if it's colliding (and returns the resultant vector) and "collideWithEntity" just triggers the collide event for each object.
However, there is an error here where im not telling the collide method to not resolve the collisions (which speeds it up, less operations), so good catch anyway.

File: static/game/bullet.js (hunk 17 above)
Comment (Matt-Puentes) [reply static/game/bullet.js]: Old debug feature, never removed.

File: package.json (hunk 19 above)
Comment (Matt-Puentes) [reply package.json]: oops

File: static/modules/entity.js (hunk 16 above)
Comment (Matt-Puentes) [reply static/modules/entity.js]: Oops. Fixed in new commit
Revealed a bug where entities were being falsely reported as not colliding when the two entities had no velocity, which was fixed.

File: static/modules/entity.js (hunk 12 above)
Comment (Matt-Puentes) [reply static/modules/entity.js]: This is specifically because an entities TerrainCollisionShape can be not defined, which means that it does not have a seperate shape for terrain collision and the normal one should be used.

File: static/modules/collision.js [hunk 23]
```diff
@@ -73,195 +68,554 @@ export function collideWithWorld(entity) {
...
     entity.pos = entity.pos.sub(mv);
 
     // bounce based on the move vector
     if (entity.reflectsOffWalls) {
-      if (mv.x !== 0) entity.vel.x *= -1;
-      if (mv.y !== 0) entity.vel.y *= -1;
-      if (hitEntities.length > 0 && entity.wallReflectSpeed !== 0) {
-        entity.vel = entity.vel.norm2().mult(entity.wallReflectSpeed);
+      if (hitTerrain.length > 0 && entity.wallReflectSpeed !== 0) {
+        entity.vel = entity.vel.norm2().mult(-entity.wallReflectSpeed);
```
Comment (jojonium) [inline static/modules/collision.js]: If an entity has `reflectsOffWalls = true` but `wallReflectSpeed = 0` it should reflect with the same speed it hit the wall with. See the description of `wallReflectSpeed` in `entity.js`
